# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            WOSPM
tagline:          'Welcoming Open Source Project Metrics'
description:      'This organization is for creating and maintaining documents and tools to measure how an open source project welcomes users and possible contributor.'
url:              https://wospm.info/
baseurl:          https://wospm.info/
logo:             https://wospm.info/assets/img/wospm_logo.png

author:
  name:           'Umut Işık'
  url:            https://twitter.com/umutphp

paginate:         5

# Custom vars
version:          2.0

github:
  repo:           https://github.com/WOSPM
